
name: publish

on: [ push ]

jobs:
  test:
    env :
      PRIVATE_TOKEN : ${{ secrets.PRIVATE_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        node-version: [ 20.x, 21.x ]
    if: "startsWith( github.event.head_commit.message, 'version' ) && startsWith( github.ref, 'refs/tags/v' )"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test

  publish:
    needs: test
    if: "startsWith( github.event.head_commit.message, 'version' ) && startsWith( github.ref, 'refs/tags/v' )"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: alice-biometrics/release-creator/@v1.0.5
        with:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_TOKEN }}
          version: ${{ github.ref_name }}
          description: ${{ github.event.head_commit.message }}
          branch: master
          prerelease: false
          draft: false

